name: Build and Release AD
on:
  push:
    branches:
      - "new"

jobs:
  Build-AD:
    strategy:
      matrix:
        java: [14]

    name: Build and Release AD Plugin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout AD
        uses: actions/checkout@v1

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Run build
        run: |
          ./gradlew buildPackages --console=plain -Dbuild.snapshot=false
          deb_artifact=`ls build/distributions/*.deb`
          aws s3 cp $deb_artifact s3://staging.artifacts.opendistroforelasticsearch.amazon.com/repos/all-old-debs/
